"""Add finding, recommendation, and auditor_notes to project_responses

Revision ID: 07f0fc12159f
Revises: f11d354bc877
Create Date: 2026-02-25 15:22:16.969457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f0fc12159f'
down_revision: Union[str, None] = 'f11d354bc877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_responses', sa.Column('finding', sa.Text(), nullable=True))
    op.add_column('project_responses', sa.Column('recommendation', sa.Text(), nullable=True))
    op.add_column('project_responses', sa.Column('auditor_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_responses', 'auditor_notes')
    op.drop_column('project_responses', 'recommendation')
    op.drop_column('project_responses', 'finding')
    # ### end Alembic commands ###
