"""Add parent_project_id for sub-projects (scope segments)

Revision ID: 08c4d3bae742
Revises: 07f0fc12159f
Create Date: 2026-02-25 15:55:20.421874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08c4d3bae742'
down_revision: Union[str, None] = '07f0fc12159f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('parent_project_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'projects', 'projects', ['parent_project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'parent_project_id')
    # ### end Alembic commands ###
