"""add workflow columns and execution table

Revision ID: 34e2eecf829c
Revises: 3bbfa6f83651
Create Date: 2026-02-25 12:22:35.839120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34e2eecf829c'
down_revision: Union[str, None] = '3bbfa6f83651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_executions',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('framework_control_id', sa.Uuid(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_node_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='workflowexecutionstatus'), nullable=False),
    sa.Column('generated_finding', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['framework_control_id'], ['framework_controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'framework_control_id', name='uq_workflow_project_control')
    )
    op.add_column('framework_controls', sa.Column('requirements_text', sa.Text(), nullable=True))
    op.add_column('framework_controls', sa.Column('testing_procedures_text', sa.Text(), nullable=True))
    op.add_column('framework_controls', sa.Column('workflow_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('framework_controls', 'workflow_definition')
    op.drop_column('framework_controls', 'testing_procedures_text')
    op.drop_column('framework_controls', 'requirements_text')
    op.drop_table('workflow_executions')
    # ### end Alembic commands ###
