"""add check_points_text to framework_controls

Revision ID: 3dc774582e7c
Revises: 08c4d3bae742
Create Date: 2026-02-26 10:53:52.430729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dc774582e7c'
down_revision: Union[str, None] = '08c4d3bae742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('framework_controls', sa.Column('check_points_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('framework_controls', 'check_points_text')
    # ### end Alembic commands ###
