"""add project observations and update evidence files model

Revision ID: 63934f31f78a
Revises: 3dc774582e7c
Create Date: 2026-02-26 12:07:10.822134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63934f31f78a'
down_revision: Union[str, None] = '3dc774582e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_observations',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('framework_control_id', sa.Uuid(), nullable=False),
    sa.Column('observation_text', sa.Text(), nullable=False),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['framework_control_id'], ['framework_controls.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('project_evidence_files', sa.Column('project_observation_id', sa.Uuid(), nullable=False))
    op.add_column('project_evidence_files', sa.Column('evidence_type', sa.String(length=50), nullable=False))
    op.add_column('project_evidence_files', sa.Column('content', sa.Text(), nullable=True))
    op.alter_column('project_evidence_files', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('project_evidence_files', 'file_path',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.drop_constraint(op.f('project_evidence_files_project_response_id_fkey'), 'project_evidence_files', type_='foreignkey')
    op.create_foreign_key(None, 'project_evidence_files', 'project_observations', ['project_observation_id'], ['id'])
    op.drop_column('project_evidence_files', 'project_response_id')
    op.drop_column('project_evidence_files', 'file_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_evidence_files', sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('project_evidence_files', sa.Column('project_response_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project_evidence_files', type_='foreignkey')
    op.create_foreign_key(op.f('project_evidence_files_project_response_id_fkey'), 'project_evidence_files', 'project_responses', ['project_response_id'], ['id'])
    op.alter_column('project_evidence_files', 'file_path',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('project_evidence_files', 'filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('project_evidence_files', 'content')
    op.drop_column('project_evidence_files', 'evidence_type')
    op.drop_column('project_evidence_files', 'project_observation_id')
    op.drop_table('project_observations')
    # ### end Alembic commands ###
