"""add assessment_checklist column to framework_controls

Revision ID: f11d354bc877
Revises: 34e2eecf829c
Create Date: 2026-02-25 15:08:28.208606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f11d354bc877'
down_revision: Union[str, None] = '34e2eecf829c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('framework_controls', sa.Column('assessment_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('framework_controls', 'assessment_checklist')
    # ### end Alembic commands ###
